[package]
name = "tower-grpc-build"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"

[dependencies]
prost-build = "0.4"
heck = "0.3"

[dependencies.codegen]
git = "https://github.com/carllerche/codegen"
rev = "9b2f818"
